### ISSUE TITLE
Allow user to specify of custom fastq file regex in config

### ISSUE THREAD

**Issue by cgates** [umich-brcf-bioinf/Watermelon#16]
By default, Watermelon will recognize fastq that match this filename regex:
.*_R(\d+)\.fastq.*
It would be groovy if the user could specify their own regex in the config. Maybe the config would be pre-populated with the default value and user could override?
cg

**Comment by twsaari** [comment]
Yeah that's something I was moving toward. This is part of the stuff that I'd like to abstract out of the pipeline itself though. I can add it in the config section for now but as an experimental, use at your own risk, type of thing
